<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>StellaSetup</AssemblyName>
    <RootNamespace>StellaSetup</RootNamespace>
    <ApplicationIcon>Assets\Stella.ico</ApplicationIcon>
    <Version>1.7.0</Version>
  </PropertyGroup>
  <ItemGroup Condition="Exists('Payload\payload.zip')">
    <EmbeddedResource Include="Payload\payload.zip" LogicalName="Stella.Payload.zip" />
  </ItemGroup>
</Project>
